apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatgptproxy
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - chatgptproxy.cwsh.top
    secretName: tls-secret
  rules:
  - host: chatgptproxy.cwsh.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chatgptproxy
            port:
              number: 80

