apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaskdemo
spec:
  rules:
  - host: flaskdemo.cwsh.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flaskdemo
            port:
              number: 80
  ingressClassName: nginx

