apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lb-service
spec:
  rules:
  - host: lb-service.cwsh.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lb-service
            port:
              number: 80
  ingressClassName: nginx

